# Generated by Django 4.2 on 2026-03-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('numero_serie', models.CharField(max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('Bicicletas', 'Bicicletas'), ('Neveras', 'Neveras'), ('Oro', 'Oro'), ('Plata', 'Plata'), ('Ollas', 'Ollas'), ('VideoJuegos', 'Videojuegos'), ('Relojes', 'Relojes'), ('Computadores', 'Computadores'), ('Otro', 'Otro')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Empeñado', 'Empeñado'), ('Vendido', 'Vendido'), ('Vencido', 'Vencido')], default='Disponible', max_length=10)),
                ('precio_sugerido_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quilataje', models.CharField(choices=[('18K', '18K'), ('16K', '16K'), ('14K', '14K'), ('10K', '10K'), ('0', '0')], max_length=3, null=True)),
            ],
            options={
                'db_table': 'articulos',
            },
        ),
    ]
