# Generated by Django 4.2 on 2026-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='estado',
            field=models.CharField(choices=[('En venta', 'En venta'), ('Empeñado', 'Empeñado'), ('Vendido', 'Vendido'), ('Vencido', 'Vencido')], default='Disponible', max_length=10),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='quilataje',
            field=models.CharField(choices=[('18', '18'), ('16', '16'), ('14', '14'), ('10', '10'), ('0', '0')], max_length=3, null=True),
        ),
    ]
