# Generated by Django 6.0.4 on 2026-05-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulos_estado_alter_articulos_quilataje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='estado',
            field=models.CharField(choices=[('En venta', 'En venta'), ('Empeñado', 'Empeñado'), ('Vendido', 'Vendido'), ('Retirado', 'Retirado')], default='Disponible', max_length=10),
        ),
    ]
