# Generated by Django 4.2 on 2026-03-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('fecha_programada', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=10)),
            ],
            options={
                'db_table': 'cuotas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=15)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('id_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empenos.cuota')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Empeno',
            fields=[
                ('id_empeno', models.AutoField(primary_key=True, serialize=False)),
                ('monto_prestado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Retirado', 'Retirado'), ('Vencido', 'Vencido')], default='Activo', max_length=10)),
                ('monto_entregado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.articulos')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'db_table': 'empenos',
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='id_empeno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empenos.empeno'),
        ),
    ]
