# Generated by Django 4.2 on 2026-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empeno',
            name='num_cuotas',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empeno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En venta', 'En venta'), ('Vencido', 'Vencido'), ('Vendido', 'Vendido')], default='Activo', max_length=10),
        ),
    ]
