# Generated by Django 4.2 on 2026-03-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_tipo_contrato'),
        ('empenos', '0002_empeno_num_cuotas_alter_empeno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='id_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato'),
        ),
    ]
