# Generated by Django 4.2 on 2026-03-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_tipo_contrato'),
        ('empenos', '0003_pago_id_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='empeno',
            name='id_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='empeno',
            name='num_cuotas',
            field=models.IntegerField(default=1),
        ),
    ]
