# Generated by Django 4.2 on 2026-03-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_departamento_expedicion'),
        ('empenos', '0004_empeno_id_contrato_alter_empeno_num_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
