# Generated by Django 6.0.4 on 2026-05-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0005_cuota_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empeno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En venta', 'En venta'), ('Vencido', 'Vencido'), ('Vendido', 'Vendido')], default='Activo', max_length=20),
        ),
    ]
