# Generated by Django 6.0.4 on 2026-05-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0006_alter_empeno_estado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pago',
            table=None,
        ),
    ]
