# Generated by Django 6.0.5 on 2026-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empenos', '0007_alter_pago_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empeno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En venta', 'En venta'), ('Vencido', 'Vencido'), ('Vendido', 'Vendido'), ('Retirado', 'Retirado')], default='Activo', max_length=20),
        ),
    ]
