# Generated by Django 4.2 on 2026-03-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('articulos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=15)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_articulo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='articulos.articulos')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
            ],
            options={
                'db_table': 'detalle_factura',
            },
        ),
    ]
