# Generated by Django 4.2 on 2026-04-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulos_estado_alter_articulos_quilataje'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='id_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.articulos'),
        ),
    ]
