# Generated by Django 6.0.4 on 2026-05-19 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulos_estado'),
        ('factura', '0002_alter_detallefactura_id_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion_servicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_empeno_asociado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Venta', 'Venta Directa de Artículo'), ('Desembolso', 'Desembolso de Empeño (Salida de Caja)'), ('Cuota', 'Pago de Cuota / Interés (Entrada de Caja)'), ('Abono', 'Abono a Capital (Entrada de Caja)'), ('Retiro', 'Liquidación y Retiro de Artículo (Entrada de Caja)')], default='Venta', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='id_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.articulos'),
        ),
        migrations.AlterModelTable(
            name='detallefactura',
            table='detalles_factura',
        ),
    ]
