# Generated by Django 4.2 on 2026-03-12 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
    ]
