# Generated by Django 4.2 on 2026-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_id_usuario_alter_cliente_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
