# Generated by Django 4.2 on 2026-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_lugar_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento_expedicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
