# Generated by Django 4.2 on 2026-03-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_departamento_expedicion'),
        ('articulos', '0002_alter_articulos_estado_alter_articulos_quilataje'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_reventa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], default='Disponible', max_length=15)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='articulos.articulos')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.cliente')),
                ('id_factura_compra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_origen', to='factura.factura')),
                ('id_factura_venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_venta', to='factura.factura')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
    ]
