# Generated by Django 4.2 on 2026-04-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('En Venta', 'En Venta'), ('Vendido', 'Vendido')], default='En Venta', max_length=15),
        ),
        migrations.CreateModel(
            name='VentaArticulo',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_venta_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('utilidad_generada', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='compras.compra')),
                ('id_factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='factura.factura')),
            ],
            options={
                'db_table': 'venta_articulo',
            },
        ),
    ]
