# Generated by Django 4.2 on 2026-04-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_estado_ventaarticulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaarticulo',
            name='fecha_venta',
        ),
        migrations.AlterField(
            model_name='ventaarticulo',
            name='utilidad_generada',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterModelTable(
            name='ventaarticulo',
            table=None,
        ),
    ]
