# Generated by Django 6.0.4 on 2026-05-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_ventaarticulo_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
