# Generated by Django 4.2 on 2026-03-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empenos', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('Normal', 'Normal'), ('Plazo Maximo', 'Plazo Maximo'), ('Contrato sobre Oro', 'Contrato sobre Oro')], max_length=20, null=True)),
                ('estado_contrato', models.CharField(choices=[('Disponible', 'Disponible'), ('Vencido', 'Vencido'), ('Retirado', 'Retirado')], max_length=10, null=True)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.articulos')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('id_cuota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empenos.cuota')),
                ('id_empeno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empenos.empeno')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
    ]
