# Generated by Django 4.2 on 2026-03-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('empenos', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='id_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.factura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empenos.pago'),
        ),
    ]
