# Generated by Django 4.2 on 2026-03-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Plazo Maximo', 'Plazo Maximo'), ('Contrato sobre Oro', 'Contrato sobre Oro'), ('Oro Maximo', 'Oro Maximo')], max_length=20, null=True),
        ),
    ]
